name       : qt5-sensors
version    : 5.10.0
release    : 8
source     :
    - https://download.qt.io/official_releases/qt/5.10/5.10.0/submodules/qtsensors-everywhere-src-5.10.0.tar.xz : cd98c5afb25bdb243b03a8e1da1a9643fbad334549c8128328446d0818fe3971
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Sensors Module
description: |
    The Qt Sensors API provides access to sensor hardware via QML and C++ interfaces. The Qt Sensors API also provides a motion gesture recognition API for devices.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtsensors.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
