name       : qt5-sensors
version    : 5.6.2
release    : 1
source     :
    - http://download.qt.io/official_releases/qt/5.6/5.6.2/submodules/qtsensors-opensource-src-5.6.2.tar.xz : a7809081aab4f2f0d7a4f40c3abb02e1690bb390d1dd410d7c6c5019a5053427
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Sensors Module
description: |
    The Qt Sensors API provides access to sensor hardware via QML and C++ interfaces. The Qt Sensors API also provides a motion gesture recognition API for devices.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos :
        /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtsensors.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
