name       : qt5-sensors
version    : 5.13.2
release    : 17
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtsensors-everywhere-src-5.13.2.tar.xz : 46f73bbfddfd78a419c6424d6839318774b84c955a7f7a96c12c590f6d8fb177
homepage   : https://www.qt.io
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Sensors Module
description: |
    The Qt Sensors API provides access to sensor hardware via QML and C++ interfaces. The Qt Sensors API also provides a motion gesture recognition API for devices.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtsensors.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
