name       : qt5-sensors
version    : 5.15.3
release    : 24
source     :
    - git|https://invent.kde.org/qt/qt/qtsensors.git : 921a31375f29e429e95352b08b2b9dbfea663cb1
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Sensors Module
description: |
    The Qt Sensors API provides access to sensor hardware via QML and C++ interfaces. The Qt Sensors API also provides a motion gesture recognition API for devices.
builddeps  :
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtsensors.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
